name: Run Shell Scripts Based on PR Label

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  determine-script:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine script to run
        id: script
        shell: bash
        run: |
          labels=$(echo '${{ toJson(github.event.pull_request.labels.*.name) }}' | jq -r '.[]')
          echo $labels
          if [[ "$labels" == *"migrate_restart"* ]]; then
            echo "migrate_and_restart" 
          elif [[ "$labels" == *"migrate"* ]]; then
            echo "migrate." 
          elif [[ "$labels" == *"restart"* ]]; then
            echo "restart"
          else
            echo "migrate_and_restart" >> $GITHUB_OUTPUT
          fi
          

